# coding: utf-8

"""
    Common Fate

    Common Fate API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.provider_config_validation import ProviderConfigValidation
from openapi_client import configuration


class TestProviderConfigValidation(unittest.TestCase):
    """ProviderConfigValidation unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
