# coding: utf-8

"""
    Approvals

    Granted Approvals API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import jhc_cf_sdk_test
from jhc_cf_sdk_test.model.groups import Groups
from jhc_cf_sdk_test import configuration


class TestGroups(unittest.TestCase):
    """Groups unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
