# coding: utf-8

"""
    Approvals

    Granted Approvals API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import jhc_cf_sdk_test
from jhc_cf_sdk_test.model.request_status import RequestStatus
from jhc_cf_sdk_test import configuration


class TestRequestStatus(unittest.TestCase):
    """RequestStatus unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
