# coding: utf-8

"""
    Approvals

    Granted Approvals API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from jhc_cf_sdk_test.paths.api_v1_admin_access_rules.post import AdminCreateAccessRule
from jhc_cf_sdk_test.paths.api_v1_admin_access_rules_rule_id.get import AdminGetAccessRule
from jhc_cf_sdk_test.paths.api_v1_admin_access_rules_rule_id_versions_version.get import AdminGetAccessRuleVersion
from jhc_cf_sdk_test.paths.api_v1_admin_access_rules_rule_id_versions.get import AdminGetAccessRuleVersions
from jhc_cf_sdk_test.paths.api_v1_admin_deployment_version.get import AdminGetDeploymentVersion
from jhc_cf_sdk_test.paths.api_v1_admin_access_rules.get import AdminListAccessRules
from jhc_cf_sdk_test.paths.api_v1_admin_requests.get import AdminListRequests
from jhc_cf_sdk_test.paths.api_v1_admin_access_rules_rule_id.put import AdminUpdateAccessRule
from jhc_cf_sdk_test.paths.api_v1_admin_groups_group_id.put import AdminUpdateGroup
from jhc_cf_sdk_test.paths.api_v1_admin_providersetups_providersetup_id_complete.post import CompleteProvidersetup
from jhc_cf_sdk_test.paths.api_v1_admin_groups.post import CreateGroup
from jhc_cf_sdk_test.paths.api_v1_admin_users.post import CreateUser
from jhc_cf_sdk_test.paths.api_v1_admin_groups_group_id.get import GetGroup
from jhc_cf_sdk_test.paths.api_v1_admin_providers_provider_id.get import GetProvider
from jhc_cf_sdk_test.paths.api_v1_admin_providers_provider_id_args.get import GetProviderArgs
from jhc_cf_sdk_test.paths.api_v1_admin_providersetups_providersetup_id.get import GetProvidersetup
from jhc_cf_sdk_test.paths.api_v1_admin_providersetups_providersetup_id_instructions.get import GetProvidersetupInstructions
from jhc_cf_sdk_test.paths.api_v1_admin_users.get import GetUsers
from jhc_cf_sdk_test.paths.api_v1_admin_identity.get import IdentityConfiguration
from jhc_cf_sdk_test.paths.api_v1_admin_identity_sync.post import IdentitySync
from jhc_cf_sdk_test.paths.api_v1_admin_groups.get import ListGroups
from jhc_cf_sdk_test.paths.api_v1_admin_providers_provider_id_args_arg_id_options.get import ListProviderArgOptions
from jhc_cf_sdk_test.paths.api_v1_admin_providers.get import ListProviders
from jhc_cf_sdk_test.paths.api_v1_admin_providersetups.get import ListProvidersetups
from jhc_cf_sdk_test.paths.api_v1_admin_providersetups_providersetup_id_steps_step_index_complete.put import SubmitProvidersetupStep
from jhc_cf_sdk_test.paths.api_v1_admin_users_user_id.post import UpdateUser
from jhc_cf_sdk_test.paths.api_v1_admin_providersetups_providersetup_id_validate.post import ValidateProvidersetup


class AdminApi(
    AdminCreateAccessRule,
    AdminGetAccessRule,
    AdminGetAccessRuleVersion,
    AdminGetAccessRuleVersions,
    AdminGetDeploymentVersion,
    AdminListAccessRules,
    AdminListRequests,
    AdminUpdateAccessRule,
    AdminUpdateGroup,
    CompleteProvidersetup,
    CreateGroup,
    CreateUser,
    GetGroup,
    GetProvider,
    GetProviderArgs,
    GetProvidersetup,
    GetProvidersetupInstructions,
    GetUsers,
    IdentityConfiguration,
    IdentitySync,
    ListGroups,
    ListProviderArgOptions,
    ListProviders,
    ListProvidersetups,
    SubmitProvidersetupStep,
    UpdateUser,
    ValidateProvidersetup,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
