# coding: utf-8

"""
    Common Fate

    Common Fate API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from jhc_cf_sdk_test.paths.api_v1_access_rules_lookup.get import AccessRuleLookup
from jhc_cf_sdk_test.paths.api_v1_admin_access_rules_rule_id_archive.post import AdminArchiveAccessRule
from jhc_cf_sdk_test.paths.api_v1_admin_groups_group_id.delete import AdminDeleteGroup
from jhc_cf_sdk_test.paths.api_v1_admin_providersetups.post import CreateProvidersetup
from jhc_cf_sdk_test.paths.api_v1_favorites_id.delete import DeleteFavorite
from jhc_cf_sdk_test.paths.api_v1_admin_providersetups_providersetup_id.delete import DeleteProvidersetup
from jhc_cf_sdk_test.paths.api_v1_favorites_id.put import UpdateFavorite
from jhc_cf_sdk_test.paths.api_v1_favorites.post import UserCreateFavorite
from jhc_cf_sdk_test.paths.api_v1_favorites_id.get import UserGetFavorite
from jhc_cf_sdk_test.paths.api_v1_favorites.get import UserListFavorites
from jhc_cf_sdk_test.paths.api_v1_requests_past.get import UserListRequestsPast
from jhc_cf_sdk_test.paths.api_v1_requests_upcoming.get import UserListRequestsUpcoming


class DefaultApi(
    AccessRuleLookup,
    AdminArchiveAccessRule,
    AdminDeleteGroup,
    CreateProvidersetup,
    DeleteFavorite,
    DeleteProvidersetup,
    UpdateFavorite,
    UserCreateFavorite,
    UserGetFavorite,
    UserListFavorites,
    UserListRequestsPast,
    UserListRequestsUpcoming,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
