# coding: utf-8

"""
    Common Fate

    Common Fate API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.api_v1_admin_access_rules_rule_id_archive.post import AdminArchiveAccessRule
from openapi_client.paths.api_v1_admin_access_rules.post import AdminCreateAccessRule
from openapi_client.paths.api_v1_admin_groups_group_id.delete import AdminDeleteGroup
from openapi_client.paths.api_v1_admin_access_rules_rule_id.get import AdminGetAccessRule
from openapi_client.paths.api_v1_admin_access_rules_rule_id_versions_version.get import AdminGetAccessRuleVersion
from openapi_client.paths.api_v1_admin_access_rules_rule_id_versions.get import AdminGetAccessRuleVersions
from openapi_client.paths.api_v1_admin_deployment_version.get import AdminGetDeploymentVersion
from openapi_client.paths.api_v1_admin_access_rules.get import AdminListAccessRules
from openapi_client.paths.api_v1_admin_requests.get import AdminListRequests
from openapi_client.paths.api_v1_admin_access_rules_rule_id.put import AdminUpdateAccessRule
from openapi_client.paths.api_v1_admin_groups_group_id.put import AdminUpdateGroup
from openapi_client.paths.api_v1_admin_providersetups_providersetup_id_complete.post import CompleteProvidersetup
from openapi_client.paths.api_v1_admin_groups.post import CreateGroup
from openapi_client.paths.api_v1_admin_providersetups.post import CreateProvidersetup
from openapi_client.paths.api_v1_admin_users.post import CreateUser
from openapi_client.paths.api_v1_admin_providersetups_providersetup_id.delete import DeleteProvidersetup
from openapi_client.paths.api_v1_admin_groups_group_id.get import GetGroup
from openapi_client.paths.api_v1_admin_providers_provider_id.get import GetProvider
from openapi_client.paths.api_v1_admin_providers_provider_id_args.get import GetProviderArgs
from openapi_client.paths.api_v1_admin_providersetups_providersetup_id.get import GetProvidersetup
from openapi_client.paths.api_v1_admin_providersetups_providersetup_id_instructions.get import GetProvidersetupInstructions
from openapi_client.paths.api_v1_admin_users.get import GetUsers
from openapi_client.paths.api_v1_admin_identity.get import IdentityConfiguration
from openapi_client.paths.api_v1_admin_identity_sync.post import IdentitySync
from openapi_client.paths.api_v1_admin_groups.get import ListGroups
from openapi_client.paths.api_v1_admin_providers_provider_id_args_arg_id_options.get import ListProviderArgOptions
from openapi_client.paths.api_v1_admin_providers.get import ListProviders
from openapi_client.paths.api_v1_admin_providersetups.get import ListProvidersetups
from openapi_client.paths.api_v1_admin_providersetups_providersetup_id_steps_step_index_complete.put import SubmitProvidersetupStep
from openapi_client.paths.api_v1_admin_users_user_id.post import UpdateUser
from openapi_client.paths.api_v1_admin_providersetups_providersetup_id_validate.post import ValidateProvidersetup


class AdminApi(
    AdminArchiveAccessRule,
    AdminCreateAccessRule,
    AdminDeleteGroup,
    AdminGetAccessRule,
    AdminGetAccessRuleVersion,
    AdminGetAccessRuleVersions,
    AdminGetDeploymentVersion,
    AdminListAccessRules,
    AdminListRequests,
    AdminUpdateAccessRule,
    AdminUpdateGroup,
    CompleteProvidersetup,
    CreateGroup,
    CreateProvidersetup,
    CreateUser,
    DeleteProvidersetup,
    GetGroup,
    GetProvider,
    GetProviderArgs,
    GetProvidersetup,
    GetProvidersetupInstructions,
    GetUsers,
    IdentityConfiguration,
    IdentitySync,
    ListGroups,
    ListProviderArgOptions,
    ListProviders,
    ListProvidersetups,
    SubmitProvidersetupStep,
    UpdateUser,
    ValidateProvidersetup,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
