# coding: utf-8

"""
    Common Fate

    Common Fate API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.api_v1_access_rules_lookup.get import AccessRuleLookup
from openapi_client.paths.api_v1_admin_requests_request_id.get import AdminGetRequest
from openapi_client.paths.api_v1_requests_request_id_cancel.post import CancelRequest
from openapi_client.paths.api_v1_favorites_id.delete import DeleteFavorite
from openapi_client.paths.api_v1_requests_request_id_access_instructions.get import GetAccessInstructions
from openapi_client.paths.api_v1_requests_request_id_access_token.get import GetAccessToken
from openapi_client.paths.api_v1_users_me.get import GetMe
from openapi_client.paths.api_v1_users_user_id.get import GetUser
from openapi_client.paths.api_v1_requests_request_id_events.get import ListRequestEvents
from openapi_client.paths.api_v1_access_rules.get import ListUserAccessRules
from openapi_client.paths.api_v1_requests_request_id_review.post import ReviewRequest
from openapi_client.paths.api_v1_requests_requestid_revoke.post import RevokeRequest
from openapi_client.paths.api_v1_favorites_id.put import UpdateFavorite
from openapi_client.paths.api_v1_favorites.post import UserCreateFavorite
from openapi_client.paths.api_v1_requests.post import UserCreateRequest
from openapi_client.paths.api_v1_access_rules_rule_id.get import UserGetAccessRule
from openapi_client.paths.api_v1_access_rules_rule_id_approvers.get import UserGetAccessRuleApprovers
from openapi_client.paths.api_v1_favorites_id.get import UserGetFavorite
from openapi_client.paths.api_v1_requests_request_id.get import UserGetRequest
from openapi_client.paths.api_v1_favorites.get import UserListFavorites
from openapi_client.paths.api_v1_requests.get import UserListRequests
from openapi_client.paths.api_v1_requests_past.get import UserListRequestsPast
from openapi_client.paths.api_v1_requests_upcoming.get import UserListRequestsUpcoming


class EndUserApi(
    AccessRuleLookup,
    AdminGetRequest,
    CancelRequest,
    DeleteFavorite,
    GetAccessInstructions,
    GetAccessToken,
    GetMe,
    GetUser,
    ListRequestEvents,
    ListUserAccessRules,
    ReviewRequest,
    RevokeRequest,
    UpdateFavorite,
    UserCreateFavorite,
    UserCreateRequest,
    UserGetAccessRule,
    UserGetAccessRuleApprovers,
    UserGetFavorite,
    UserGetRequest,
    UserListFavorites,
    UserListRequests,
    UserListRequestsPast,
    UserListRequestsUpcoming,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
