name: Clone/Build SDK from OpenAPI

on:
  push:
    paths:
      - 'release-versions/*'

# steps involved
# on new release trigger a clone/build using the new version
# - extract the version from the release-versions/tags-latest.txt file
# i.e. https://raw.githubusercontent.com/common-fate/common-fate/[VERSION/openapi.yml
# - install the file into a /ci-temp dir
# - run the generate-on-ci command
# - commit the changes to the repo

jobs:
  get-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Get latest release version
        id: get_version
        run: |
          echo ::set-output name=version::$(cat release-versions/tags-latest.txt)
          echo $(cat release-versions/tags-latest.txt)

  # Now we can access the version number using ${{ steps.get_version.outputs.version }}
  clone-openapi:
    runs-on: ubuntu-latest
    needs: get-tag
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Download openapi-generator-cli.jar artifact
        uses: actions/download-artifact@v3
        with:
          name: openapi-generator-cli.jar
          path: modules/openapi-generator-cli/target
      - name: Clone OpenAPI
        run: |
          mkdir ci-temp
          cd ci-temp
          curl -sL https://raw.githubusercontent.com/common-fate/common-fate/${{ steps.get_version.outputs.version }}/openapi.yml > openapi.yml
      - name: Build SDK
        run: |
          make generate-on-ci
      - name: Cleanup
        run: |
          rm -rf ci-temp
      - name: Commit changes
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@users.noreply.github.com'
          git commit -am "New release version"
          git push
