name: Clone/Build SDK from OpenAPI

on:
  push:
    paths:
      - 'release-versions/*'

# steps involved
# on new release trigger a clone/build using the new version
# - extract the version from the release-versions/tags-latest.txt file
# i.e. https://raw.githubusercontent.com/common-fate/common-fate/[VERSION/openapi.yml
# - install the file into a /ci-temp dir
# - run the generate-on-ci command
# - commit the changes to the repo

jobs:
  clone-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Get latest release version
        id: get_version
        run: |
          echo $(cat release-versions/tags-latest.txt)
          echo "::set-output name=version::$(cat release-versions/tags-latest.txt)"
      - name: Clone OpenAPI
        run: |
          mkdir ci-temp
          cd ci-temp
          curl -sL https://raw.githubusercontent.com/common-fate/common-fate/${{ steps.get_version.outputs.version }}/openapi.yml > openapi.yml      # https://github.com/marketplace/actions/generate-client-library-w-the-openapitools-generator
      - name: Install OpenAPI Generator
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: python
          # config-file: openapi-generator-config.json
          openapi-file: ci-temp/openapi.yml
          command-args: --package-name=jhc_cf_sdk_test
          # alternatively may use:
          # openapi-url: https://raw.githubusercontent.com/common-fate/common-fate/${{ steps.get_version.outputs.version }}/openapi.yml
      - name: Build SDK
        run: |
          make generate-on-ci
      - name: Cleanup
        run: |
          rm -rf ci-temp
      - name: Commit changes
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@users.noreply.github.com'
          git commit -am "New release version"
          git push
